import 'dotenv/config';
import express from 'express';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import {PrismaClient} from '@prisma/client';
import {z} from 'zod';
import {totals,types,prefixes} from '../shared/billing.js';
import path from 'node:path';
const app=express(), db=new PrismaClient();
const secret=process.env.JWT_SECRET;
if(!secret||secret.length<32)console.warn('Login needs JWT_SECRET. Run: node server/configure-secret.js');
if(!process.env.DATABASE_URL)console.warn('Connected accounts need DATABASE_URL in .env. See README.md for PostgreSQL setup.');
app.use(helmet({contentSecurityPolicy:false}));app.use(express.json({limit:'1mb'}));
const wrap=fn=>(req,res,next)=>Promise.resolve(fn(req,res,next)).catch(next);
app.get('/api/health',wrap(async(req,res)=>{await db.$queryRaw`SELECT 1`;res.json({ok:true});}));
app.post('/api/login',rateLimit({windowMs:900000,limit:30}),wrap(async(req,res)=>{
  if(!secret||secret.length<32)return res.status(503).json({error:'Configure JWT_SECRET (32+ characters) on the server.'});
  if(!process.env.DATABASE_URL)return res.status(503).json({error:'Connected login needs PostgreSQL. Set DATABASE_URL in .env, then run npm run db:push and npm run db:seed. For users created in the demo, select Demo workspace on the login page.'});
  const {username,password,remember}=z.object({username:z.string().min(1),password:z.string().min(1),remember:z.boolean().optional()}).parse(req.body);
  const user=await db.user.findUnique({where:{username}});
  if(!user?.enabled||!await bcrypt.compare(password,user.password))return res.status(401).json({error:'Invalid username or password.'});
  res.json({token:jwt.sign({sub:user.id},secret,{expiresIn:remember?'30d':'8h'}),user:publicUser(user)});
}));
const publicUser=({password,...u})=>u;
app.use('/api',wrap(async(req,res,next)=>{try{const claims=jwt.verify((req.headers.authorization||'').replace('Bearer ',''),secret);req.user=await db.user.findUnique({where:{id:claims.sub}});}catch{return res.status(401).json({error:'Please log in again.'});}if(!req.user?.enabled)return res.status(401).json({error:'Account disabled.'});next();}));
app.get('/api/me',(req,res)=>res.json(publicUser(req.user)));
const clientSchema=z.object({name:z.string().trim().min(1),company:z.string().trim().min(1),address:z.string().min(1),city:z.string().min(1),state:z.string().min(1),pincode:z.string().regex(/^\d{6}$/),gst:z.string().refine(v=>!v||/^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][1-9A-Z]Z[0-9A-Z]$/.test(v),'Invalid GSTIN'),phone:z.string().regex(/^[+\d ()-]{7,20}$/),email:z.string().email()});
app.get('/api/clients',wrap(async(req,res)=>res.json(await db.client.findMany({orderBy:{company:'asc'}}))));
app.post('/api/clients',wrap(async(req,res)=>res.json(await db.client.create({data:clientSchema.parse(req.body)}))));
app.put('/api/clients/:id',wrap(async(req,res)=>res.json(await db.client.update({where:{id:req.params.id},data:clientSchema.parse(req.body)}))));
app.delete('/api/clients/:id',wrap(async(req,res)=>{await db.client.delete({where:{id:req.params.id}});res.json({ok:true});}));
const num=(max=10000000)=>z.coerce.number().finite().min(0).max(max);
const docSchema=z.object({type:z.enum(types),clientId:z.string().min(1),date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),dueDate:z.string().optional(),status:z.enum(['Pending','Paid','Draft','Overdue']).default('Pending'),items:z.array(z.object({description:z.string().min(1),hsn:z.string(),qty:num(100000).positive(),rate:num()})).min(1),discount:num(100).default(0),cgst:num(100).default(0),sgst:num(100).default(0),igst:num(100).default(0),rounding:z.coerce.number().min(-100).max(100).default(0),quotationNo:z.string().default(''),proformaNo:z.string().default(''),challanNo:z.string().default(''),poNo:z.string().default(''),poDate:z.string().default(''),vendorCode:z.string().default(''),transport:z.string().default(''),terms:z.string().default('')}).refine(d=>!(d.igst&&(d.cgst||d.sgst)),'Use IGST or CGST + SGST, not both');
app.get('/api/documents',wrap(async(req,res)=>res.json(await db.document.findMany({include:{client:true},orderBy:{createdAt:'desc'}}))));
async function documentData(body){const d=docSchema.parse(body);const total=z.number().min(0).max(999999999999.99).parse(totals(d).total);return {type:d.type,status:d.status,clientId:d.clientId,date:new Date(d.date),dueDate:d.dueDate?new Date(d.dueDate):null,total,data:d};}
app.post('/api/documents',wrap(async(req,res)=>{const data=await documentData(req.body);const doc=await db.$transaction(async tx=>{const row=await tx.document.create({data:{...data,number:`TEMP-${crypto.randomUUID()}`}});return tx.document.update({where:{id:row.id},data:{number:`${prefixes[data.type]}-${new Date(data.date).getFullYear()}-${String(row.sequence).padStart(4,'0')}`},include:{client:true}});});res.json(doc);}));
app.put('/api/documents/:id',wrap(async(req,res)=>{const data=await documentData(req.body);const existing=await db.document.findUniqueOrThrow({where:{id:req.params.id}});if(existing.type!==data.type)return res.status(400).json({error:'Document type cannot be changed.'});res.json(await db.document.update({where:{id:req.params.id},data,include:{client:true}}));}));
app.delete('/api/documents/:id',wrap(async(req,res)=>{await db.document.delete({where:{id:req.params.id}});res.json({ok:true});}));
app.use('/api/users',(req,res,next)=>req.user.role==='Admin'?next():res.status(403).json({error:'Admin access required.'}));
app.get('/api/users',wrap(async(req,res)=>res.json((await db.user.findMany()).map(publicUser))));
const userSchema=z.object({name:z.string().min(1),username:z.string().min(3),password:z.string().min(8).optional(),role:z.enum(['Admin','Staff']),enabled:z.boolean()});
app.post('/api/users',wrap(async(req,res)=>{const data=userSchema.parse(req.body);if(!data.password)return res.status(400).json({error:'Password is required.'});data.password=await bcrypt.hash(data.password,12);res.json(publicUser(await db.user.create({data})));}));
app.put('/api/users/:id',wrap(async(req,res)=>{const data=userSchema.parse(req.body);if(req.params.id===req.user.id&&(!data.enabled||data.role!=='Admin'))return res.status(400).json({error:'You cannot disable or demote your own account.'});if(data.password)data.password=await bcrypt.hash(data.password,12);res.json(publicUser(await db.user.update({where:{id:req.params.id},data})));}));
app.delete('/api/users/:id',wrap(async(req,res)=>{if(req.params.id===req.user.id)return res.status(400).json({error:'You cannot delete your own account.'});await db.user.delete({where:{id:req.params.id}});res.json({ok:true});}));
app.use('/api',(req,res)=>res.status(404).json({error:'Endpoint not found.'}));
app.use(express.static(path.resolve('dist')));app.get('*',(req,res)=>res.sendFile(path.resolve('dist/index.html')));
app.use((err,req,res,next)=>{console.error(err.message);const error=err instanceof z.ZodError?err.issues.map(i=>`${i.path.join('.')}: ${i.message}`).join('; '):err.code==='P2003'?'This client has documents and cannot be deleted.':err.code==='P2002'?'That username or number already exists.':'Unable to complete request. Check the server and database connection.';res.status(err instanceof z.ZodError?400:err.code==='P2025'?404:409).json({error});});
app.listen(process.env.PORT||3001,()=>console.log('Ruby API running on port '+(process.env.PORT||3001)));
