import React,{useState,useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import {LayoutDashboard,FileText,Files,MessageSquareText,Truck,History,Users,LogOut,Search,Bell,ChevronDown,ArrowUpRight,ArrowDownRight,Plus,ArrowRight,Download,MoreHorizontal,X,Menu,Check,Eye,EyeOff,Trash2,Pencil,Copy,Building2,Wallet,IndianRupee,CheckCircle2,Clock,ShieldCheck,HelpCircle,ChevronLeft,ChevronRight,SlidersHorizontal,CalendarDays,LoaderCircle,ArrowLeft,ExternalLink} from 'lucide-react';
import {AreaChart,Area,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer} from 'recharts';
import {initialDemo,removeSampleInvoice} from './demo';
import {prepareDemoUser} from './demoAuth';
import LoginScreen from './LoginScreen';
import ReferencePreview from './ReferencePreview';
import {money,totals,words,types,prefixes} from '../shared/billing';
import {downloadPDF} from './pdf';
import './styles.css';

const nav=[['Dashboard',LayoutDashboard],['Invoice',FileText],['Proforma',Files],['Quotes',MessageSquareText],['Delivery Challan',Truck],['History',History],['Clients',Building2],['Users',Users]];
const today=()=>new Date().toISOString().slice(0,10);
const emptyClient={name:'',company:'',address:'',city:'',state:'Maharashtra',pincode:'',gst:'',phone:'',email:''};
const blankDoc=type=>({type,date:today(),clientId:'',status:'Pending',quotationNo:'',proformaNo:'',challanNo:'',poNo:'',poDate:today(),vendorCode:'',transport:'',items:[{description:'',hsn:'',qty:1,rate:0}],discount:0,cgst:9,sgst:9,igst:0,rounding:0,terms:'All Disputes are Subject to Mumbai jurisdiction Only.'});
function Logo(){return <div className="brand"><img className="brand-logo" src="/branding/v6-logo.png" alt="Ruby Hydraulic Co." width="1268" height="305"/><small>INVOICE & BILLING</small></div>}
function App(){
 const [session,setSession]=useState(()=>{try{return JSON.parse(sessionStorage.getItem('ruby-session')||localStorage.getItem('ruby-session')||'null')}catch{return null}});
 const [demo,setDemo]=useState(!session||session.mode==='demo'),[login,setLogin]=useState(false),[page,setPage]=useState('Dashboard'),[mobile,setMobile]=useState(false),[store,setStore]=useState(()=>{try{return removeSampleInvoice(JSON.parse(localStorage.getItem('ruby-demo'))||initialDemo())}catch{return initialDemo()}}),[busy,setBusy]=useState(false),[toast,setToast]=useState(null),[modal,setModal]=useState(null),[editing,setEditing]=useState(null),[search,setSearch]=useState(''),[notification,setNotification]=useState(false);
 const user=demo?(session?.mode==='demo'?store.users.find(u=>u.id===session.user.id):store.users.find(u=>u.id==='u1')):session?.user;
 function notify(message,error=false){setToast({message,error});}
 useEffect(()=>{const handle=e=>notify(e.detail,true);window.addEventListener('ruby-error',handle);return()=>window.removeEventListener('ruby-error',handle)},[]);
 useEffect(()=>{if(toast){const timer=setTimeout(()=>setToast(null),4500);return()=>clearTimeout(timer)}},[toast]);
 useEffect(()=>{if(demo)localStorage.setItem('ruby-demo',JSON.stringify(store));},[store,demo]);
 useEffect(()=>{if(demo&&session?.mode==='demo'&&!user?.enabled){logout();notify('Your account is disabled or no longer exists. Contact your administrator.',true)}},[demo,session,user?.enabled]);
 useEffect(()=>{const sync=e=>{if(demo&&e.key==='ruby-demo'&&e.newValue){try{setStore(removeSampleInvoice(JSON.parse(e.newValue)))}catch{}}};window.addEventListener('storage',sync);return()=>window.removeEventListener('storage',sync)},[demo]);
 async function api(endpoint,method='GET',body){const r=await fetch('/api'+endpoint,{method,headers:{'Content-Type':'application/json',Authorization:`Bearer ${session?.token}`},...(body?{body:JSON.stringify(body)}:{})});const result=await r.json();if(!r.ok){if(r.status===401){setLogin(true);setSession(null);sessionStorage.removeItem('ruby-session');localStorage.removeItem('ruby-session');}throw Error(result.error||'Request failed');}return result;}
 async function load(){setBusy(true);try{const [clients,documents,me]=await Promise.all([api('/clients'),api('/documents'),api('/me')]);const users=me.role==='Admin'?await api('/users'):[];setStore({clients,documents,users});}catch(e){notify(e.message,true)}finally{setBusy(false)}}
 useEffect(()=>{if(session&&!demo)load()},[session,demo]);
 function go(p){setPage(p);setEditing(null);setSearch('');setMobile(false)}
  async function save(collection,data){setBusy(true);try{if(collection==='users'&&user?.role!=='Admin')throw Error('Admin access required.');let saved;if(demo){saved={...data,id:data.id||crypto.randomUUID()};if(collection==='documents'){saved={...saved,total:totals(data).total,data:{...data},client:store.clients.find(c=>c.id===data.clientId),number:data.number||`${prefixes[data.type]}-${new Date().getFullYear()}-${String(Math.max(128,...store.documents.map(d=>Number(d.number.split('-').at(-1))||0))+1).padStart(4,'0')}`,createdAt:data.createdAt||new Date().toISOString()};}if(collection==='users'){saved=await prepareDemoUser(saved,store.users);}setStore(s=>({...s,[collection]:data.id?s[collection].map(v=>v.id===data.id?saved:v):[saved,...s[collection]]}));}else{const payload={...data};if(collection==='users'&&!payload.password)delete payload.password;saved=await api('/'+collection+(data.id?'/'+data.id:''),data.id?'PUT':'POST',payload);setStore(s=>({...s,[collection]:data.id?s[collection].map(v=>v.id===data.id?saved:v):[saved,...s[collection]]}));}notify(collection==='users'?'User saved. They can now log in to this workspace.':'Successfully saved');return saved;}catch(e){notify(e.message,true);return null;}finally{setBusy(false)}}
 async function remove(collection,id){setBusy(true);try{if(collection==='users'&&user?.role!=='Admin')throw Error('Admin access required.');if(demo&&collection==='clients'&&store.documents.some(d=>d.clientId===id))throw Error('This client has documents and cannot be deleted.');if(collection==='users'&&id===user.id)throw Error('You cannot delete your own account.');if(!demo)await api('/'+collection+'/'+id,'DELETE');setStore(s=>({...s,[collection]:s[collection].filter(v=>v.id!==id)}));setModal(null);notify('Deleted successfully');}catch(e){notify(e.message,true)}finally{setBusy(false)}}
 function editDoc(d,duplicate=false){setEditing({...d.data,id:duplicate?undefined:d.id,number:duplicate?undefined:d.number,status:duplicate?'Draft':d.status,clientId:d.clientId});setPage(d.type);setModal(null)}
 function logout(){localStorage.setItem('ruby-login-mode',demo?'demo':'connected');setSession(null);setDemo(false);setLogin(true);localStorage.removeItem('ruby-session');sessionStorage.removeItem('ruby-session');setMobile(false);setModal(null);setPage('Dashboard')}
 const hydrated=store.documents.map(d=>({...d,client:store.clients.find(c=>c.id===d.clientId)||d.client}));
 if(login)return <><LoginScreen Logo={Logo} onDemo={()=>{setStore(()=>{try{return removeSampleInvoice(JSON.parse(localStorage.getItem('ruby-demo'))||initialDemo())}catch{return initialDemo()}});setSession(null);localStorage.removeItem('ruby-session');sessionStorage.removeItem('ruby-session');setDemo(true);setLogin(false);setModal(null);go('Dashboard')}} onLogin={s=>{setStore(s.mode==='demo'?removeSampleInvoice(JSON.parse(localStorage.getItem('ruby-demo'))):{clients:[],documents:[],users:[]});setSession(s);setDemo(s.mode==='demo');setLogin(false);setModal(null);go('Dashboard')}}/>{toast&&<div className="toast error">{toast.message}</div>}</>;
 return <div className="app-shell">
  {mobile&&<div className="sidebar-overlay" onClick={()=>setMobile(false)}/>}
  <aside className={'sidebar '+(mobile?'open':'')}><Logo/><div className="workspace"><div className="workspace-icon">RH</div><div><strong>Ruby Hydraulic</strong><small>Business workspace</small></div><ChevronDown size={15}/></div><div className="nav-label">WORKSPACE</div><nav>{nav.filter(([p])=>p!=='Users'||user?.role==='Admin').map(([p,Icon])=><button key={p} className={page===p?'active':''} onClick={()=>go(p)}><Icon size={19}/><span>{p}</span>{p==='Invoice'&&<span className="nav-count">{store.documents.filter(d=>d.type==='Invoice').length}</span>}{page===p&&<span className="active-dot"/>}</button>)}</nav><div className="sidebar-bottom"><div className="help-card"><div className="help-icon"><HelpCircle size={21}/></div><strong>A little help?</strong><p>Everything you need to keep<br/>your business moving.</p><button onClick={()=>setModal({kind:'help'})}>Visit help center <ArrowUpRight size={15}/></button></div><button className="logout" onClick={logout}><LogOut size={18}/>Logout</button><div className="sidebar-foot"><span className="online-dot"/>All systems operational <span>v1.0</span></div></div></aside>
  <div className="main-shell"><header className="topbar"><div className="top-left"><button className="icon-button mobile-toggle" onClick={()=>setMobile(!mobile)} aria-label="Toggle menu"><Menu size={21}/></button><span className="breadcrumb">Workspace <ChevronRight size={14}/> <strong>{page}</strong></span></div><div className="top-actions"><div className="global-search"><Search size={17}/><input aria-label="Search documents" placeholder="Search anything..." value={search} onChange={e=>{setSearch(e.target.value);if(page!=='History')setPage('History')}}/><kbd>⌘ K</kbd></div><div className="notifications"><button className="icon-button bell" aria-label="Notifications" onClick={()=>setNotification(!notification)}><Bell size={20}/><i/></button>{notification&&<div className="notification-pop"><strong>Payment reminders</strong><p>{store.documents.filter(d=>d.status==='Pending').length} documents are awaiting payment.</p><button className="text-button" onClick={()=>{go('History');setNotification(false)}}>View your documents <ArrowRight size={14}/></button></div>}</div><div className="top-divider"/><button className="profile" onClick={()=>setModal({kind:'profile'})}><div className="avatar">{user?.name?.split(' ').map(n=>n[0]).join('').slice(0,2)}</div><div><strong>{user?.name}</strong><small>{user?.role==='Admin'?'Administrator':'Staff member'}</small></div><ChevronDown size={15}/></button></div></header>
  <main>{demo&&<div className="demo-banner"><span><span className="online-dot"/>Demo workspace <span className="demo-detail">· Explore with sample data. Changes are saved in this browser.</span></span><button onClick={()=>setLogin(true)}>Sign in to your workspace <ArrowUpRight size={13}/></button></div>}
   {busy&&<div className="loading-line"/>}
   {page==='Dashboard'?<Dashboard documents={hydrated} clients={store.clients} user={user} go={go} onView={d=>setModal({kind:'view',doc:d})} onNew={()=>go('Invoice')}/>:
   types.includes(page)?<Billing key={page+(editing?.id||'new')+(editing?.number||'')} type={page} initial={editing} clients={store.clients} documents={hydrated} busy={busy} onClient={()=>setModal({kind:'client',data:{...emptyClient},onAdded:true})} newClient={modal?.selectedClient} onSave={async(d,pdf)=>{const total=totals(d).total;if(total<0||total>999999999999.99)return notify('Total must be between ₹0 and ₹999,999,999,999.99. Check items and rounding.',true);const saved=await save('documents',d);if(saved){if(pdf)downloadPDF(saved);go('History')}}} onCancel={()=>go('History')}/>:
   page==='History'?<HistoryPage documents={hydrated} clients={store.clients} search={search} setSearch={setSearch} onNew={()=>go('Invoice')} onView={d=>setModal({kind:'view',doc:d})} onEdit={editDoc} onDelete={d=>setModal({kind:'delete',collection:'documents',id:d.id,name:d.number})} onDuplicate={d=>editDoc(d,true)}/>:
   page==='Clients'?<Clients clients={store.clients} onAdd={()=>setModal({kind:'client',data:{...emptyClient}})} onEdit={data=>setModal({kind:'client',data})} onDelete={c=>setModal({kind:'delete',collection:'clients',id:c.id,name:c.company})}/>:
   <UsersPage users={store.users} onAdd={()=>setModal({kind:'user',data:{name:'',username:'',password:'',role:'Staff',enabled:true}})} onEdit={data=>setModal({kind:'user',data:{...data,password:''}})} onDelete={u=>setModal({kind:'delete',collection:'users',id:u.id,name:u.name})}/>}
   <footer className="page-footer"><span>© {new Date().getFullYear()} Ruby Hydraulic. All rights reserved.</span><span><ShieldCheck size={13}/> Secure. Simple. Seamless.</span></footer>
  </main></div>
  {modal&&modal.kind&&<Modal title={{client:modal.data?.id?'Edit client':'Add new client',user:modal.data?.id?'Edit user':'Add new user',delete:'Delete '+modal.name+'?',view:'Document preview',help:'Your billing, made simple',profile:'Your account'}[modal.kind]} onClose={()=>setModal(null)} wide={modal.kind==='view'}>
   {modal.kind==='client'&&<ClientForm data={modal.data} busy={busy} onSave={async data=>{const c=await save('clients',data);if(c)setModal(modal.onAdded?{selectedClient:c.id}:null)}} onCancel={()=>setModal(null)}/>}
   {modal.kind==='user'&&<UserForm data={modal.data} busy={busy} onSave={async data=>{if(demo&&data.id===user.id&&(!data.enabled||data.role!=='Admin'))return notify('You cannot disable or demote your own account.',true);if(await save('users',data))setModal(null)}} onCancel={()=>setModal(null)}/>}
   {modal.kind==='delete'&&<><p className="muted">This will permanently delete this record. This action cannot be undone.</p><div className="modal-actions"><button className="btn" onClick={()=>setModal(null)}>Cancel</button><button disabled={busy} className="btn danger" onClick={()=>remove(modal.collection,modal.id)}>{busy?'Deleting…':'Delete record'}</button></div></>}
    {modal.kind==='view'&&<><div className="document-status-control"><label htmlFor="document-status">Document status</label><select id="document-status" disabled={busy} value={modal.doc.status} onChange={async e=>{const saved=await save('documents',{...modal.doc.data,id:modal.doc.id,number:modal.doc.number,status:e.target.value});if(saved)setModal({kind:'view',doc:saved})}}>{['Pending','Paid','Draft','Overdue'].map(s=><option key={s}>{s}</option>)}</select></div><ReferencePreview doc={modal.doc} onEdit={()=>editDoc(modal.doc)}/></>}
   {modal.kind==='help'&&<div className="help-content"><p>Create a document, select or add a client, and enter your item details. Ruby calculates taxes and totals automatically.</p><h3>Keep everything in one place</h3><p>Use History to search, edit, duplicate, or download any document. Manage client information from the Total clients card on the dashboard.</p><h3>Ready for your business?</h3><p>Sign in with your administrator-provided account to use the connected database. The demo workspace stores sample data on this browser only.</p></div>}
   {modal.kind==='profile'&&<div className="help-content"><div className="profile-summary"><div className="avatar large">{user?.name?.[0]}</div><div><h3>{user?.name}</h3><p>{user?.role} · {demo?'Demo workspace':'Ruby Hydraulic'}</p></div></div><button className="btn" onClick={logout}><LogOut size={16}/>Sign out</button></div>}
  </Modal>}
  {toast&&<div role="status" className={'toast '+(toast.error?'error':'')} >{toast.error?<X size={18}/>:<CheckCircle2 size={18}/>} {toast.message}<button onClick={()=>setToast(null)} aria-label="Dismiss notification"><X size={14}/></button></div>}
 </div>
}

function Dashboard({documents,clients,user,go,onView,onNew}){
 const [range,setRange]=useState('6');const invoices=documents.filter(d=>d.type==='Invoice'),paid=invoices.filter(d=>d.status==='Paid'),pending=invoices.filter(d=>['Pending','Overdue'].includes(d.status));
 const sum=rows=>rows.reduce((s,d)=>s+Number(d.total),0);
 const chart=Array.from({length:Number(range)},(_,i)=>{const date=new Date();date.setDate(1);date.setMonth(date.getMonth()-Number(range)+1+i);const key=date.toISOString().slice(0,7);return {name:date.toLocaleDateString('en',{month:'short'}),revenue:sum(paid.filter(d=>d.date.slice(0,7)===key)),pending:sum(pending.filter(d=>d.date.slice(0,7)===key))};});
 const metrics=[{title:'Total invoices',value:invoices.length.toString().padStart(2,'0'),icon:FileText,color:'green',sub:'Invoices created',action:()=>go('History')},{title:'Pending payments',value:money(sum(pending)),icon:Wallet,color:'amber',sub:`${pending.length} invoices awaiting payment`,action:()=>go('History')},{title:'Total revenue',value:money(sum(paid)),icon:IndianRupee,color:'purple',sub:'From paid invoices',action:()=>go('History')},{title:'Total clients',value:clients.length.toString().padStart(2,'0'),icon:Users,color:'blue',sub:'Your growing business network',action:()=>go('Clients')}];
 return <><div className="page-heading"><div><div className="eyebrow">YOUR BUSINESS AT A GLANCE</div><h1>Welcome back, {user?.name?.split(' ')[0]} <span className="wave">👋</span></h1><p>Here’s what’s happening with your business today.</p></div><button className="btn primary" onClick={onNew}><Plus size={18}/>Create invoice</button></div>
 <div className="overview-label"><h2>Overview <span className="small-dot"/></h2><span><CalendarDays size={15}/>{new Date().toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric'})}</span></div>
 <section className="metrics">{metrics.map(({title,value,icon:Icon,color,sub,action})=><button className="metric-card" key={title} onClick={action}><div className="metric-top"><span>{title}</span><div className={'metric-icon '+color}><Icon size={20}/></div></div><div className="metric-value">{value}</div><div className="metric-bottom"><span className={'metric-indicator '+color}><ArrowUpRight size={13}/></span><span>{sub}</span><ArrowRight size={14}/></div></button>)}</section>
 <div className="chart-grid"><section className="panel revenue-panel"><div className="panel-heading"><div><h2>Revenue overview</h2><p>A little perspective on your business growth.</p></div><select aria-label="Revenue period" className="small-select" value={range} onChange={e=>setRange(e.target.value)}><option value="6">Last 6 months</option><option value="12">Last 12 months</option><option value="3">Last 3 months</option></select></div><div className="chart-summary"><strong>{money(chart.reduce((s,d)=>s+d.revenue,0))}</strong><span className="subtle-pill"><span className="online-dot"/>Paid revenue</span><div className="chart-legend"><span><i className="legend-green"/>Revenue</span><span><i className="legend-pale"/>Pending</span></div></div><div className="chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chart} margin={{left:0,right:12,top:15,bottom:0}}><defs><linearGradient id="revenueFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#24865f" stopOpacity={.2}/><stop offset="100%" stopColor="#24865f" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="4 5" vertical={false} stroke="#edf0ed"/><XAxis dataKey="name" axisLine={false} tickLine={false} tick={{fill:'#939a96',fontSize:11}} dy={10}/><YAxis axisLine={false} tickLine={false} tick={{fill:'#939a96',fontSize:10}} tickFormatter={n=>'₹'+(n/1000)+'k'} width={49}/><Tooltip formatter={v=>money(v)} contentStyle={{borderRadius:10,border:'1px solid #e8ece8',fontSize:12}}/><Area type="monotone" dataKey="pending" stroke="#b8cfc0" strokeWidth={2} strokeDasharray="5 5" fill="transparent"/><Area type="monotone" dataKey="revenue" stroke="#268361" strokeWidth={2.5} fill="url(#revenueFill)"/></AreaChart></ResponsiveContainer></div></section>
 <section className="panel quick-panel"><div className="panel-heading"><div><h2>Quick actions</h2><p>Less admin. More business.</p></div><span className="sparkle">✧</span></div><div className="quick-list">{[{title:'Create invoice',sub:'Get paid for your work',icon:FileText,page:'Invoice',color:'green'},{title:'New quotation',sub:'Turn opportunities into business',icon:MessageSquareText,page:'Quotes',color:'purple'},{title:'Create proforma',sub:'Set the details in motion',icon:Files,page:'Proforma',color:'blue'},{title:'Delivery challan',sub:'Keep your deliveries on track',icon:Truck,page:'Delivery Challan',color:'amber'}].map(({title,sub,icon:Icon,page,color})=><button key={page} onClick={()=>go(page)}><div className={'quick-icon '+color}><Icon size={19}/></div><div><strong>{title}</strong><span>{sub}</span></div><ChevronRight size={16}/></button>)}</div><div className="quick-note"><ShieldCheck size={15}/><span>Every detail, beautifully organized.</span></div></section></div>
 <section className="panel recent-panel"><div className="panel-heading"><div><h2>Recent documents <span className="count-pill">{documents.length}</span></h2><p>Your latest activity, all in one place.</p></div><button className="btn compact" onClick={()=>go('History')}>View all documents <ArrowRight size={15}/></button></div><DocumentTable documents={documents.slice(0,5)} onView={onView}/><div className="table-bottom"><span>Showing {Math.min(5,documents.length)} of {documents.length} documents</span><span><span className="online-dot"/>Up to date</span></div></section>
 <div className="bottom-banner"><div className="banner-symbol">✧</div><div><strong>Good business starts with great organization.</strong><p>You take care of your business. We’ll take care of the paperwork.</p></div><span>Made for your momentum <ArrowUpRight size={17}/></span></div></>
}
function Badge({status}){return <span className={'badge '+status.toLowerCase()}><span/>{status}</span>}
function DocumentTable({documents,onView,onEdit,onDelete,onDuplicate}){const [menu,setMenu]=useState(null);return <div className="table-scroll"><table className="data-table"><thead><tr><th>Document no.</th><th>Client / Company</th><th>Type</th><th>Date</th><th className="align-right">Amount</th><th>Status</th><th className="align-center">Action</th></tr></thead><tbody>{documents.map((d,i)=><tr key={d.id}><td><button className="document-link" onClick={()=>onView(d)}><span className="document-icon"><FileText size={15}/></span>{d.number}</button></td><td><div className="company-cell"><span className={'company-avatar tint-'+i%5}>{d.client?.company?.split(' ').map(n=>n[0]).slice(0,2).join('')}</span><div><strong>{d.client?.company}</strong><small>{d.client?.email}</small></div></div></td><td><span className="type-tag">{d.type}</span></td><td className="date-cell">{new Date(d.date).toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'})}</td><td className="align-right amount-cell">{d.type==='Delivery Challan'?'—':money(d.total)}</td><td><Badge status={d.status}/></td><td><div className="row-actions"><button className="icon-button" title="Download PDF" onClick={()=>downloadPDF(d)}><Download size={16}/></button><button className="icon-button" title="More actions" onClick={()=>setMenu(menu===d.id?null:d.id)}><MoreHorizontal size={17}/></button>{menu===d.id&&<><div className="menu-dismiss" onClick={()=>setMenu(null)}/><div className="row-menu">{[['View',Eye,()=>onView(d)],...(onEdit?[['Edit',Pencil,()=>onEdit(d)],['Duplicate',Copy,()=>onDuplicate(d)],['Delete',Trash2,()=>onDelete(d)]]:[])].map(([label,Icon,fn])=><button key={label} onClick={()=>{fn();setMenu(null)}}><Icon size={14}/>{label}</button>)}</div></>}</div></td></tr>)}</tbody></table>{!documents.length&&<div className="empty-state"><Files size={32}/><h3>No documents yet</h3><p>Create a document or adjust your filters to get started.</p></div>}</div>}
function HistoryPage({documents,clients,search,setSearch,onNew,...actions}){const [type,setType]=useState(''),[status,setStatus]=useState(''),[client,setClient]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[p,setP]=useState(1);const filtered=documents.filter(d=>(!type||d.type===type)&&(!status||d.status===status)&&(!client||d.clientId===client)&&(!from||d.date.slice(0,10)>=from)&&(!to||d.date.slice(0,10)<=to)&&`${d.number} ${d.client?.company} ${d.client?.name}`.toLowerCase().includes(search.toLowerCase()));useEffect(()=>setP(1),[type,status,client,from,to,search]);const pages=Math.max(1,Math.ceil(filtered.length/10)),current=Math.min(p,pages);return <><PageHeading eyebrow="YOUR DOCUMENT WORKSPACE" title="Document history" description="Every invoice, quote, and delivery. One organized place." action={<button className="btn primary" onClick={onNew}><Plus size={17}/>Create invoice</button>}/><section className="panel"><div className="filter-bar"><div className="filter-search"><Search size={16}/><input placeholder="Search documents or clients..." value={search} onChange={e=>setSearch(e.target.value)}/></div><select aria-label="Document type" value={type} onChange={e=>setType(e.target.value)}><option value="">All types</option>{types.map(t=><option key={t}>{t}</option>)}</select><select aria-label="Status" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{['Paid','Pending','Draft','Overdue'].map(t=><option key={t}>{t}</option>)}</select><select aria-label="Client" value={client} onChange={e=>setClient(e.target.value)}><option value="">All clients</option>{clients.map(c=><option key={c.id} value={c.id}>{c.company}</option>)}</select></div><div className="date-filter"><CalendarDays size={16}/><label>From <input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>To <input type="date" min={from} value={to} onChange={e=>setTo(e.target.value)}/></label><button className="text-button" onClick={()=>{setType('');setStatus('');setClient('');setFrom('');setTo('');setSearch('')}}>Clear filters</button></div><DocumentTable documents={filtered.slice((current-1)*10,current*10)} {...actions}/><div className="table-bottom"><span>{filtered.length} documents found</span><div className="pagination"><button disabled={current<=1} className="icon-button" onClick={()=>setP(current-1)} aria-label="Previous page"><ChevronLeft size={16}/></button><span>Page {current} of {pages}</span><button disabled={current>=pages} className="icon-button" onClick={()=>setP(current+1)} aria-label="Next page"><ChevronRight size={16}/></button></div></div></section></>}
function PageHeading({eyebrow,title,description,action}){return <div className="page-heading"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{description}</p></div>{action}</div>}
function Field({label,children,...props}){return <label className="field"><span>{label}</span>{children||<input {...props}/>}</label>}
function Billing({type,initial,clients,documents,busy,onClient,newClient,onSave,onCancel}){
 const [d,setD]=useState(initial||blankDoc(type)),[clientSearch,setClientSearch]=useState(''),[clientOpen,setClientOpen]=useState(false),[pdf,setPdf]=useState(false);const set=(k,v)=>setD(s=>({...s,[k]:v}));const c=clients.find(c=>c.id===d.clientId),t=totals(d),challan=type==='Delivery Challan';useEffect(()=>{if(newClient)set('clientId',newClient)},[newClient]);
 const updateItem=(index,key,value)=>set('items',d.items.map((item,i)=>i===index?{...item,[key]:value}:item));
 return <><PageHeading eyebrow="MAKE IT OFFICIAL" title={`${initial?.id?'Edit':'Create'} ${type.toLowerCase()}`} description="A few details now. A professional impression every time." action={<button className="btn" onClick={onCancel}><ArrowLeft size={16}/>Back to documents</button>}/><form onSubmit={e=>{e.preventDefault();if(!d.clientId){document.getElementById('client-picker').focus();return}onSave(d,pdf)}}><section className="panel billing-panel"><div className="panel-heading"><div><h2>{type==='Invoice'?'Tax invoice':type} details</h2><p>Document and company information</p></div><span className="subtle-pill"><FileText size={14}/>{d.number||'Auto-numbered on save'}</span></div><div className="billing-fields"><div className="form-grid two"><Field label="Select/Type Quotation No"><input list="quote-options" value={d.quotationNo} onChange={e=>set('quotationNo',e.target.value)} placeholder="Select or enter quotation number"/><datalist id="quote-options">{documents.filter(x=>x.type==='Quotes').map(x=><option key={x.id} value={x.number}/>)}</datalist></Field><Field label="Select/Type Proforma No"><input list="proforma-options" value={d.proformaNo} onChange={e=>set('proformaNo',e.target.value)} placeholder="Select or enter proforma number"/><datalist id="proforma-options">{documents.filter(x=>x.type==='Proforma').map(x=><option key={x.id} value={x.number}/>)}</datalist></Field></div>
 <div className="form-grid two"><Field label={type+' No.'} value={d.number||'Generated automatically on save'} readOnly/><div className="field client-field"><div className="field-label-row"><span>Company Name <b>*</b></span><button type="button" className="text-button" onClick={onClient}><Plus size={13}/>Add New Client</button></div><div className="client-picker"><input id="client-picker" required autoComplete="off" placeholder="Search and select a client" value={clientOpen?clientSearch:c?.company||''} onFocus={()=>{setClientOpen(true);setClientSearch('')}} onChange={e=>{setClientSearch(e.target.value);setClientOpen(true)}}/><ChevronDown size={16}/>{clientOpen&&<><div className="picker-dismiss" onClick={()=>setClientOpen(false)}/><div className="client-options">{clients.filter(c=>`${c.company} ${c.name}`.toLowerCase().includes(clientSearch.toLowerCase())).map(c=><button type="button" key={c.id} onClick={()=>{set('clientId',c.id);setClientOpen(false)}}><Building2 size={16}/><span>{c.company}<small>{c.name} · {c.city}</small></span>{c.id===d.clientId&&<Check size={16}/>}</button>)}{!clients.filter(c=>`${c.company} ${c.name}`.toLowerCase().includes(clientSearch.toLowerCase())).length&&<p>No clients found. Add a new client.</p>}</div></>}</div></div>
 <Field label="Company Address"><textarea readOnly value={c?`${c.address}, ${c.city}, ${c.state} ${c.pincode}`:''} placeholder="Auto-filled from selected client" rows={2}/></Field><Field label="Company Contact no" readOnly value={c?.phone||''} placeholder="Auto-filled from selected client"/><Field label="Company Email" readOnly value={c?.email||''} placeholder="Auto-filled from selected client"/><Field label="State" readOnly value={c?.state||''} placeholder="Auto-filled from selected client"/><Field label="GSTIN" readOnly value={c?.gst||''} placeholder="Auto-filled from selected client"/><Field label="Date" type="date" required value={d.date} onChange={e=>set('date',e.target.value)}/><Field label="Challan Number" value={d.challanNo} onChange={e=>set('challanNo',e.target.value)}/><Field label="PO NO" value={d.poNo} onChange={e=>set('poNo',e.target.value)}/><Field label="Date P.O No" type="date" value={d.poDate} onChange={e=>set('poDate',e.target.value)}/><Field label="Vendor Code" value={d.vendorCode} onChange={e=>set('vendorCode',e.target.value)}/><Field label="Transport Reference" value={d.transport} onChange={e=>set('transport',e.target.value)}/></div></div></section>
 <section className="panel billing-panel">
  <div className="panel-heading item-heading"><div><h2>Item details <span className="count-pill">{d.items.length} items</span></h2><p>Add the products or services for this document.</p></div><button className="btn compact" type="button" onClick={()=>set('items',[...d.items,{description:'',hsn:'',qty:1,rate:0}])}><Plus size={15}/>Add item</button></div>
  <div className="table-scroll"><table className="item-table"><thead><tr><th>#</th><th>Particular</th><th>HSN</th><th>Quantity</th>{!challan&&<><th>Rate</th><th>Amount</th></>}<th/></tr></thead><tbody>{d.items.map((item,i)=><tr key={i}>
   <td>{String(i+1).padStart(2,'0')}</td><td><textarea rows={item.description.includes('\n')?6:2} aria-label={`Particular ${i+1}`} required value={item.description} placeholder={'Product name\nProduct description'} onChange={e=>updateItem(i,'description',e.target.value)}/></td>
   <td><input aria-label={`HSN ${i+1}`} value={item.hsn} placeholder="HSN/SAC" onChange={e=>updateItem(i,'hsn',e.target.value)}/></td><td><input aria-label={`Quantity ${i+1}`} type="number" min="0.001" max="100000" step="any" required value={item.qty} onChange={e=>updateItem(i,'qty',e.target.value)}/></td>
   {!challan&&<><td><input aria-label={`Rate ${i+1}`} type="number" required min="0" max="10000000" step="0.01" value={item.rate} onChange={e=>updateItem(i,'rate',e.target.value)}/></td><td className="amount-cell">{money(item.qty*item.rate)}</td></>}
   <td><button type="button" aria-label="Remove item" disabled={d.items.length===1} className="icon-button delete-icon" onClick={()=>set('items',d.items.filter((_,index)=>i!==index))}><Trash2 size={16}/></button></td>
  </tr>)}</tbody></table></div>
  <div className="billing-summary"><div className="terms-col"><Field label="Terms And conditions"><textarea rows={5} value={d.terms} onChange={e=>set('terms',e.target.value)}/></Field>{!challan&&<div className="amount-words"><span>AMOUNT IN WORDS</span><p>{words(Math.max(0,t.total))}</p></div>}</div>{!challan&&<div className="totals-col"><div><span>Discount (%)</span><input aria-label="Discount percentage" type="number" min="0" max="100" step="0.01" value={d.discount} onChange={e=>set('discount',e.target.value)}/></div><div><span>Total Taxable Amount</span><strong>{money(t.taxable)}</strong></div>{['cgst','sgst','igst'].map(key=><div key={key}><span>{key.toUpperCase()}</span><div className="tax-input"><input aria-label={key+' percent'} type="number" min="0" max="100" step="0.01" value={d[key]} onChange={e=>setD(s=>({...s,[key]:e.target.value,...(Number(e.target.value)>0?key==='igst'?{cgst:0,sgst:0}:{igst:0}:{})}))}/><span>%</span></div><strong>{money(t[key])}</strong></div>)}<div><span>Rounding Off</span><input aria-label="Rounding off" type="number" min="-100" max="100" step="0.01" value={d.rounding} onChange={e=>set('rounding',e.target.value)}/></div><div className="grand-total"><strong>Total Payable Amount</strong><strong>{money(t.total)}</strong></div></div>}</div>
 </section><div className="form-bottom"><span><ShieldCheck size={15}/>Your document is ready for a professional impression.</span><div><button type="button" className="btn" onClick={onCancel}>Cancel</button><button className="btn" disabled={busy} onClick={()=>setPdf(false)} type="submit">{busy?<LoaderCircle className="spin" size={16}/>:<Check size={16}/>}Save</button><button className="btn primary" type="submit" disabled={busy} onClick={()=>setPdf(true)}><Download size={16}/>Save & Download PDF</button></div></div></form></>
}
function Clients({clients,onAdd,onEdit,onDelete}){const [q,setQ]=useState('');return <><PageHeading eyebrow="YOUR BUSINESS CONNECTIONS" title="Clients" description="Good relationships start with the right details." action={<button className="btn primary" onClick={onAdd}><Plus size={17}/>Add client</button>}/><section className="panel"><div className="filter-bar"><div className="filter-search"><Search size={17}/><input placeholder="Search clients..." value={q} onChange={e=>setQ(e.target.value)}/></div><span className="muted">{clients.length} clients</span></div><div className="table-scroll"><table className="data-table"><thead><tr><th>Company</th><th>Contact</th><th>Location</th><th>GSTIN</th><th>Actions</th></tr></thead><tbody>{clients.filter(c=>`${c.company} ${c.name}`.toLowerCase().includes(q.toLowerCase())).map(c=><tr key={c.id}><td><strong>{c.company}</strong><small className="block muted">{c.name}</small></td><td>{c.email}<small className="block muted">{c.phone}</small></td><td>{c.city}, {c.state}</td><td>{c.gst||'—'}</td><td><div className="row-actions"><button aria-label="Edit client" className="icon-button" onClick={()=>onEdit(c)}><Pencil size={16}/></button><button aria-label="Delete client" className="icon-button delete-icon" onClick={()=>onDelete(c)}><Trash2 size={16}/></button></div></td></tr>)}</tbody></table></div>{!clients.length&&<div className="empty-state">Add your first client to get started.</div>}</section></>}
function ClientForm({data,busy,onSave,onCancel}){const [c,setC]=useState(data);return <form onSubmit={e=>{e.preventDefault();onSave(c)}}><div className="form-grid two">{[['name','Name'],['company','Company'],['address','Address'],['city','City'],['state','State'],['pincode','Pincode'],['gst','GST/Tax number'],['phone','Phone'],['email','Email']].map(([key,label])=><Field key={key} label={label} value={c[key]} required={key!=='gst'} type={key==='email'?'email':'text'} pattern={key==='pincode'?'[0-9]{6}':key==='phone'?'[+0-9 ()-]{7,20}':key==='gst'?'[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][1-9A-Z]Z[0-9A-Z]':undefined} title={key==='gst'?'Enter a valid 15-character GSTIN':key==='pincode'?'Enter a 6-digit pincode':undefined} onChange={e=>setC({...c,[key]:key==='gst'?e.target.value.toUpperCase():e.target.value})}/>)}</div><div className="modal-actions"><button type="button" className="btn" onClick={onCancel}>Cancel</button><button disabled={busy} className="btn primary">{busy?'Saving…':'Save client'}</button></div></form>}
function UsersPage({users,onAdd,onEdit,onDelete}){return <><PageHeading eyebrow="BETTER TOGETHER" title="Team members" description="Manage your team and their workspace access." action={<button className="btn primary" onClick={onAdd}><Plus size={17}/>Add user</button>}/><section className="panel"><div className="panel-heading"><h2>All users <span className="count-pill">{users.length}</span></h2><ShieldCheck size={20}/></div><div className="table-scroll"><table className="data-table"><thead><tr><th>Name</th><th>Username</th><th>Role</th><th>Access</th><th>Actions</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><div className="company-cell"><span className="company-avatar tint-0">{u.name[0]}</span><strong>{u.name}</strong></div></td><td>{u.username}</td><td><span className="type-tag">{u.role}</span></td><td><span className={'badge '+(u.enabled?'paid':'draft')}><span/>{u.enabled?'Enabled':'Disabled'}</span></td><td><div className="row-actions"><button aria-label="Edit user" className="icon-button" onClick={()=>onEdit(u)}><Pencil size={16}/></button><button aria-label="Delete user" className="icon-button delete-icon" onClick={()=>onDelete(u)}><Trash2 size={16}/></button></div></td></tr>)}</tbody></table></div></section></>}
function UserForm({data,busy,onSave,onCancel}){const [u,setU]=useState(data);return <form onSubmit={e=>{e.preventDefault();onSave(u)}}><div className="form-grid two"><Field label="Full name" required value={u.name} onChange={e=>setU({...u,name:e.target.value})}/><Field label="Username" required minLength={3} value={u.username} onChange={e=>setU({...u,username:e.target.value})}/><Field label={u.id?'New password (leave blank to keep)':'Password'} type="password" minLength={8} required={!u.id} value={u.password} onChange={e=>setU({...u,password:e.target.value})}/><Field label="Role"><select value={u.role} onChange={e=>setU({...u,role:e.target.value})}><option>Admin</option><option>Staff</option></select></Field><label className="checkbox"><input type="checkbox" checked={u.enabled} onChange={e=>setU({...u,enabled:e.target.checked})}/>Enable account access</label></div><div className="modal-actions"><button type="button" className="btn" onClick={onCancel}>Cancel</button><button disabled={busy} className="btn primary">{busy?'Saving…':'Save user'}</button></div></form>}
function Modal({title,onClose,wide,children}){useEffect(()=>{const handler=e=>{if(e.key==='Escape')onClose()};document.addEventListener('keydown',handler);const old=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.removeEventListener('keydown',handler);document.body.style.overflow=old}},[]);return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section role="dialog" aria-modal="true" aria-label={title} className={'modal '+(wide?'wide':'')}><div className="modal-header"><h2>{title}</h2><button autoFocus aria-label="Close dialog" className="icon-button" onClick={onClose}><X size={20}/></button></div><div className="modal-body">{children}</div></section></div>}

createRoot(document.getElementById('root')).render(<App/>);
